# Generated by Django 3.0.5 on 2020-04-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='betting',
            name='created',
        ),
        migrations.AlterField(
            model_name='betting',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
