# Generated by Django 3.0.5 on 2020-04-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200420_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='betting',
            name='checksum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='betting',
            name='option',
            field=models.CharField(max_length=100),
        ),
    ]
