# Generated by Django 3.0.5 on 2020-07-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-updated_at']},
        ),
    ]
