# Generated by Django 3.0.5 on 2020-06-07 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0008_auto_20200606_2050'),
        ('blog', '0005_auto_20200525_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UserProfile.UserProfile'),
        ),
    ]
