# Generated by Django 3.0.5 on 2020-06-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200608_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='description',
            new_name='caption',
        ),
    ]
