# Generated by Django 3.1 on 2021-01-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200616_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
