# Generated by Django 3.1 on 2021-01-27 15:48

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210127_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media/', validators=[blog.validators.validate_media]),
        ),
    ]
