# Generated by Django 3.1 on 2021-01-28 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210128_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
