# Generated by Django 3.0.5 on 2020-05-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200525_0707'),
        ('UserProfile', '0004_auto_20200525_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.blog'),
        ),
    ]
