# Generated by Django 3.0.5 on 2020-05-28 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_userprofile_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='posts',
        ),
    ]
